name: Activity type & filter
on:
  pull_request:
    types: [opened, closed] #https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#pull_request
    branches:
      - main
  workflow_dispatch:  
  push:
    branches:
      - main
      - 'dev-*'    #dev-new, dev-this-is-new
      - 'feat/**'  #feat/new, , feat/new/button
    paths-ignore:  #https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore
      -'README.md'
jobs: 
  first-job:
    runs-on: ubuntu-latest #https://docs.github.com/ru/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
    steps: 
      - name: Print greeting
        run: echo "Hello World"
      - name: Get code
        uses: actions/checkout@v4  #https://github.com/marketplace?category=&type=actions&verification=&query=checkout  
      - name: Print goodbye
        run: |  # to run multiple shell commands
          echo "Done!"
          echo "Bye-bye!"
      
