name: Output Workflow
on: workflow_dispatch
jobs:
  info:
    runs-on: ubuntu-latest
    steps:
      - name: Output Github Context  #https://docs.github.com/en/actions/learn-github-actions/contexts
        run: echo "${{ toJSON(github) }}"   #https://docs.github.com/en/actions/learn-github-actions/expressions
    
