name: First Workflow
on: workflow_dispatch
jobs: 
  first-job:
    runs-on: ubuntu-latest #https://docs.github.com/ru/actions/using-github-hosted-runners/about-github-hosted-runners/about-github-hosted-runners
    steps: 
      - name: Print greeting
        run: echo "Hello World"
      - name: Print goodbye
        run: echo "Done- bye!
      
